---
# tasks file for repo_passenger
- name: Check if I`m on Ubuntu
  fail: "This role is for Debian-like systems only"
  when: ansible_os_family != "Debian"

- name: Ensure apt repository key is available
  apt_key: url="http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x561F9B9CAC40B2F7" state={{ state }}

- name: Ensure apt repository is available
  apt_repository: repo="deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_lsb.codename }} main" state={{ state }} update_cache=yes

